### ISSUE TITLE
Codacy - Revisión proyecto

### ISSUE THREAD

**Issue by raulolles** [raulolles/TFG_GII_O_MA_18.08#50]
Utilizar codacy para testear el proyecto hasta la fecha y corregir las mejoras sugeridas.

**Comment by clopezno** [comment]
Me gusta que se apliquen en TFG los conocimientos que se adquieren en la asignatura de desarrollo avanzado de sistemas software.
Recuerda eliminar las variables no usadas y revisar el tamaño de este fichero https://app.codacy.com/app/clopezno/TFG_GII_O_MA_18.08/file/29546722294/issues/source?bid=11029743&fileBranchId=11029743

Además, los test se pueden integrar en Codacy dando aun más fuerza al proceso de  calidad continua (continuous QA).
Saludos
Carlos López
